apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubetest001-data-volume-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      storage-iops: 2000
